### PR TITLE
Add support for external media providers

### PR DESCRIPTION
**Pull request by tjerman**
Support for providers such as giphy, ...

The plugin is generalized to support any custom providers.
To add a new provider, create a new class and extend the base Provider class.
To use a provider, specify it when registering the plugin.

Ref: https://github.com/crusttech/webapp-messaging/issues/52

### CODE REVIEW

**Review by Fajfa — APPROVED** [review]

**Comment by tjerman** [comment]
Sneak peek into gifs

Screenshot from 2019-06-19 13-02-32

**Comment by darh** [comment]
Awesome!!

2 questions:
 - can we disguise this into command (`/giphy ...`) ?
 - can keep image proportions (not sure if gifs are pre-squashed or are we doing this)?

**Comment by darh** [comment]
@tjerman ^^

**Comment by tjerman** [comment]
* We can make it a slash command, yes; but I would prefer to allow both `/gif [provider optional]` and `gif [provider optional]`. I would not call the command `giphy` in case we decide to add support for other gif providers.

* I will check ratios in a bit, but if I remember correctly, I am not squishing them on purpose (will double check tho).

**Comment by darh** [comment]
Let's call it `/giphy` and have `/gif` alias for it.

**Pull request closed without merging**
